{% set name = "algviz" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/algviz-{{ version }}.tar.gz
  sha256: bab78e24f4e80c6e363728bd80de9926ef6649e54d1cc487f0f3f98ef1cc1fdc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - python-graphviz >=0.8.4,!=0.18,<=0.20.1
    - ipykernel >=6.4.0,<=6.23.1
    - ipython >=8.0.0,<=8.12.0

test:
  imports:
    - algviz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://algviz.com/
  summary: An algorithm visualization tool for jupyter notebook to show animation for vector, table, linked list, tree and graph data structures.
  license: GPL-3.0-only
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - zjl9959
    - julian-belina
